# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-calendar' : '@latest'
    'kde/pim/akonadi-mime' : '@latest'
    'kde/pim/kcalutils' : '@latest'
    'kde/pim/kidentitymanagement' : '@latest'
    'kde/pim/kimap' : '@latest'
    'kde/pim/kmime' : '@latest'
    'kde/pim/pimcommon' : '@latest'
    'kde/pim/akonadi-notes' : '@latest'
