# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5', 'macOS/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kholidays' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmime' : '@same'
    'pim/akonadi-notes' : '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
