# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/kholidays': '@latest-kf6'
    'pim/akonadi': '@same'
    'pim/akonadi-calendar': '@same'
    'pim/kcalutils': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmime': '@same'
    'libraries/ktextaddons': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
