version = 1
SPDX-PackageName = "calendarsupport"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/calendarsupport"

[[annotations]]
path = [".gersemirc", "src/next/README", ".krazy", ".clang-tidy", "src/calendarsupport-index.qdoc", "src/calendarsupport.qdoc", "src/calendarsupport.qdocconf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["README-ECMInstalledLibraryCheck.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"
